# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       nemo-configs-x86

# >> macros
# << macros

Summary:    Some configs for x86-generic adaptation in Nemo Mobile
Version:    0.1
Release:    1
Group:      Configs
License:    GPLv2
BuildArch:  noarch
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-configs-x86.yaml

%description
%{summary}.


%package vm-common
Summary:    Common files shared by both Xorg and Wayland for x86 vm adaptation
Group:      Configs
Provides:   nemo-configs-x86-vm-common
Conflicts:  nemo-configs-x86 <= 0.2.1
%description vm-common
%{summary}

%package vm-xorg
Summary:    Xorg Configs for x86 vm adaptation
Group:      Configs
Provides:   nemo-configs-x86-vm-xorg
Requires:   nemo-configs-x86-vm-common

Provides:   nemo-mobile-configs-x86-vm > 2
Obsoletes:  nemo-mobile-configs-x86-vm <= 2
#don't break current xorg images
Provides:   nemo-configs-x86-vm > 0.2.1
Obsoletes:  nemo-configs-x86-vm <= 0.2.1

%description vm-xorg
%{summary}.


%package vm-wayland
Summary:    Wayland Configs for x86 vm adaptation
Group:      Configs
Provides:   nemo-configs-x86-vm-wayland
Requires:   nemo-configs-x86-vm-common

%description vm-wayland
%{summary}.


%package generic
Summary:    Configs for generic x86 adaptation
Group:      Configs
Provides:   nemo-mobile-configs-x86-generic > 2
Obsoletes:  nemo-mobile-configs-x86-generic <= 2

%description generic
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%make_install
# << install pre

# >> install post
# << install post


%files vm-common
%defattr(-,root,root,-)
%{_sharedstatedir}/environment/nemo/61-x86-vm.conf
# >> files vm-common
# << files vm-common

%files vm-wayland 
%defattr(-,root,root,-) 
%{_sharedstatedir}/environment/compositor/61-x86-vm-ui.conf
# >> files vm-wayland
# << files vm-wayland

#Currently empty package, to give an xorg alternative to the wayland package
%files vm-xorg
# >> files vm-xorg
# << files vm-xorg

%files generic
%defattr(-,root,root,-)
%{_sharedstatedir}/environment/nemo/61-x86-generic.conf
# >> files generic
# << files generic
